name: opensea_repository
description: A Dart Repository which manages the opensea domain.
version: 1.0.0+1
homepage: https://github.com/angwonson/opensea_repository
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.0.0
#  opensea_api:
#    path: ../opensea_api
  opensea_dart: ^0.0.2

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^1.10.0
  json_serializable: ^4.0.0
  mocktail: ^0.2.0
  test: ^1.16.4
