name: opensea_api
description: A Dart API client for the OpenSea API
version: 1.0.0+1
homepage: https://github.com/angwonson/opensea_api

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.0

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^1.10.0
  json_serializable: ^4.0.0
  mocktail: ^0.2.0
  test: ^1.16.4
