name: nftpuzzlefun

on: 
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - ".github/workflows/nftpuzzlefun.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: 2.8.0
          channel: stable

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
